// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-FPH_BQhUoyU2QR3xnQY423w4q4Hjxhc',
    appId: '1:210927173824:web:99cd88bc30cfba9e566d25',
    messagingSenderId: '210927173824',
    projectId: 'volunteer-connect-167d8',
    authDomain: 'volunteer-connect-167d8.firebaseapp.com',
    storageBucket: 'volunteer-connect-167d8.firebasestorage.app',
    measurementId: 'G-W8MG3B41B8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8-LGeKYA5pJGfTESJol2LAoCW5QFvg50',
    appId: '1:210927173824:android:25dff91c00ed5b20566d25',
    messagingSenderId: '210927173824',
    projectId: 'volunteer-connect-167d8',
    storageBucket: 'volunteer-connect-167d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDg-TTD3ERFGLM-L2n9ji1BFzZDgRCEgDA',
    appId: '1:210927173824:ios:6e8a7b4e32ca8b1e566d25',
    messagingSenderId: '210927173824',
    projectId: 'volunteer-connect-167d8',
    storageBucket: 'volunteer-connect-167d8.firebasestorage.app',
    iosBundleId: 'com.example.solutionChallenge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDg-TTD3ERFGLM-L2n9ji1BFzZDgRCEgDA',
    appId: '1:210927173824:ios:6e8a7b4e32ca8b1e566d25',
    messagingSenderId: '210927173824',
    projectId: 'volunteer-connect-167d8',
    storageBucket: 'volunteer-connect-167d8.firebasestorage.app',
    iosBundleId: 'com.example.solutionChallenge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-FPH_BQhUoyU2QR3xnQY423w4q4Hjxhc',
    appId: '1:210927173824:web:0adb41541bef0735566d25',
    messagingSenderId: '210927173824',
    projectId: 'volunteer-connect-167d8',
    authDomain: 'volunteer-connect-167d8.firebaseapp.com',
    storageBucket: 'volunteer-connect-167d8.firebasestorage.app',
    measurementId: 'G-ESZ6NMZLCW',
  );
}